[programs.localnet]
cofre = "Cofre5DxTYsWtWKrby3hLVg8pM5RePf96sCa7HJMwDeZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -t 1000000 tests/**/*.ts"
# test = "npx ts-mocha -t 1000000 --inspect-brk tests/*.ts"
